### ISSUE TITLE
Jumbled KG Context in Training / Testing Data

### ISSUE THREAD

**Issue by jeremytanjianle** [mulangonando/Impact-of-KG-Context-on-ED#2]
Hi, 

I understand that one of the key contributions of the paper is to represent the triples in KG context in the natural language. However, looking through the data in the Roberta folder, the KG context seems to be jumbled up. 

For instance:  [Q8242](https://www.wikidata.org/wiki/Q8242)
Sample expected context:
`6	Q8242	Slovak literature is the literature of Slovakia. History. Middle Ages. The first monuments of literature in present-day Slovakia are 	described by source literary science studied by Jewish Encyclopedia of Brockhaus and Efron literary criticism subclass of art	1`

Sample actual context:
`6	Q8242	Slovak literature is the literature of Slovakia. History. Middle Ages. The first monuments of literature in present-day Slovakia are 	described by source Jewish Encyclopedia of Brockhaus and Efron studied by literary criticism subclass of art	1`

Should this be a concern?

Thank you

**Comment by jeremytanjianle** [comment]
Found the problem, essentially, the context builder uses a `set()` to compile the graph but the order is not saved. 

for example, in `read_data.py`, when running:
```
get_graph_from_wikidata_id('Q84')
````
The graph is gradually added as the following. Notice the breaking of the order:
```
{}
{'continent', 'Europe'}
{'England', 'continent', 'capital of', 'Europe'}
```

### Recommend the following change and re-generating the dataset again
```
#             graph_set.add(relation)
#             graph_set.add(to_item)
            graph_set.add(relation + ' ' + to_item)
```

**Comment by mulangonando** [comment]
Hi,
Sorry for the late response.
Glad you were able to figure it out.
Thanks as well, for the headsup.
